name: Update ./scripts

on:
  push:
    branches: ["main"]

jobs: 
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v3  # Note: using v3 instead of v2
      with:
        submodules: 'recursive'  # This will initialize and update submodules

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run update script
      run: |
        chmod +x scripts/update.sh
        ./scripts/update.sh

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "chore: update by GitHub Actions" || echo "No changes to commit"
        git push